"""Write the authored hillclimb-review example: Inspect-format logs for a ticket-routing
evaluation, one baseline and five proposed changes, with recorded cost per sample.

These are constructed illustrations, not model output. Every outcome and cost below is
declared in this file so the example can be regenerated byte for byte:

    python examples/hillclimb-review/build.py
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
EPOCHS = 4
TUNING = [f"route-{index:02d}" for index in range(1, 13)]
HELD_OUT = [f"holdout-{index:02d}" for index in range(1, 9)]


def outcomes(tuning_passes: dict, held_out_passes: dict, default_tuning: int, default_held: int):
    """Passing epochs (0..EPOCHS) per case; unspecified cases use the defaults."""
    table = {case: tuning_passes.get(case, default_tuning) for case in TUNING}
    table |= {case: held_out_passes.get(case, default_held) for case in HELD_OUT}
    return table


# Each step: label, model, cost per sample in USD, passing epochs per case, description.
STEPS = [
    (
        "00-baseline",
        "anthropic/opus-4.8",
        0.046,
        outcomes(
            {"route-01": 0, "route-02": 0, "route-03": 2, "route-04": 1, "route-05": 0},
            {"holdout-01": 0, "holdout-02": 2, "holdout-03": 1},
            EPOCHS,
            EPOCHS,
        ),
        "Opus 4.8, high thinking, original prompt.",
    ),
    (
        "01-prompt-audit",
        "anthropic/opus-4.8",
        0.041,
        outcomes(
            {"route-01": 2, "route-02": 3, "route-03": 4, "route-04": 3, "route-05": 1},
            {"holdout-01": 2, "holdout-02": 4, "holdout-03": 3},
            EPOCHS,
            EPOCHS,
        ),
        "Remove forced tool calls, scratchpad and contradictory rules. Kept.",
    ),
    (
        "02-refund-examples",
        "anthropic/opus-4.8",
        0.043,
        outcomes(
            {"route-01": 4, "route-02": 4, "route-03": 4, "route-04": 4, "route-05": 4},
            {"holdout-01": 2, "holdout-02": 4, "holdout-03": 3},
            EPOCHS,
            EPOCHS,
        ),
        "Paste the failing tuning tickets into the prompt. Overfits: rolled back.",
    ),
    (
        "03-opus-5.5-low",
        "anthropic/opus-5.5",
        0.019,
        outcomes(
            {"route-01": 2, "route-02": 3, "route-03": 4, "route-04": 3, "route-05": 1},
            {"holdout-01": 2, "holdout-02": 4, "holdout-03": 3},
            EPOCHS,
            EPOCHS,
        ),
        "Opus 5.5 with low thinking: same quality, lower cost. Kept.",
    ),
    (
        "04-haiku-minimal",
        "anthropic/haiku-5",
        0.004,
        outcomes(
            {"route-01": 1, "route-02": 2, "route-03": 3, "route-04": 2, "route-05": 0},
            {"holdout-01": 0, "holdout-02": 3, "holdout-03": 2},
            EPOCHS,
            EPOCHS,
        ),
        "Much cheaper model: held-out cases regress. Rolled back.",
    ),
    (
        "05-sonnet-5-low",
        "anthropic/sonnet-5",
        0.010,
        outcomes(
            {"route-01": 2, "route-02": 3, "route-03": 4, "route-04": 3, "route-05": 1},
            {"holdout-01": 2, "holdout-02": 4, "holdout-03": 3},
            EPOCHS,
            EPOCHS,
        ),
        "Sonnet 5 with low thinking: same quality, lower cost again. Kept.",
    ),
]


def log(label: str, model: str, cost: float, passes: dict) -> dict:
    samples = []
    for epoch in range(1, EPOCHS + 1):
        for case in TUNING + HELD_OUT:
            passed = epoch <= passes[case]
            answer = f"route:{case}:{'billing' if passed else 'general'}"
            samples.append(
                {
                    "id": case,
                    "epoch": epoch,
                    "input": f"Ticket {case}: customer message",
                    "target": f"route:{case}:billing",
                    "output": {"model": model, "choices": [], "completion": answer},
                    "scores": {"route": {"value": "C" if passed else "I", "answer": answer}},
                    "model_usage": {
                        model: {
                            "input_tokens": 1800,
                            "output_tokens": 200,
                            "total_tokens": 2000,
                            "total_cost": cost,
                        }
                    },
                    "working_time": 1.5,
                }
            )
    return {
        "version": 2,
        "status": "success",
        "eval": {
            "task": "ticket_routing",
            "model": model,
            "config": {"epochs": EPOCHS},
            "scorers": [{"name": "route", "options": {}}],
            "metadata": {"step": label, "authored_example": True},
        },
        "samples": samples,
    }


def main() -> None:
    (HERE / "results").mkdir(exist_ok=True)
    for label, model, cost, passes, _ in STEPS:
        path = HERE / "results" / f"{label}.json"
        path.write_text(json.dumps(log(label, model, cost, passes), indent=1) + "\n")
    split = {
        "schema_version": "evalarc.case-split.v1",
        "description": "holdout-* tickets were never shown to the tuning loop.",
        "held_out": ["holdout-*"],
    }
    (HERE / "split.json").write_text(json.dumps(split, indent=2) + "\n")


if __name__ == "__main__":
    main()
